### ISSUE TITLE
Crash when opening Anonymity Wood book page from The Last Smith Slashblade Addon

### ISSUE THREAD

**Issue by UberbeastX** [VazkiiMods/Patchouli#456]
As the subject states I try to click the page and the crash happens. Here is the report
[crash-2021-10-28_15.24.59-client.txt](https://github.com/VazkiiMods/Patchouli/files/7436921/crash-2021-10-28_15.24.59-client.txt)
.

**Comment by Hubry** [comment]
The book you tried to open failed to load properly, as the Patchouli context further in the crash report indicates. Seems like this is caused by not having Twilight Forest installed, despite the page having a config marker to block loading it. Sadly we don't really work on Patchouli for 1.12 anymore, outside of major issues showing up.

https://github.com/0999312/The-Last-Smith/issues/18

**Comment by UberbeastX** [comment]
> The book you tried to open failed to load properly, as the Patchouli context further in the crash report indicates. Seems like this is caused by not having Twilight Forest installed, despite the page having a config marker to block loading it. Sadly we don't really work on Patchouli for 1.12 anymore, outside of major issues showing up.
> 
> [0999312/The-Last-Smith#18](https://github.com/0999312/The-Last-Smith/issues/18)

Ah ok thank you, guess it's an issues on their end or one caused by the many mods I have installed. I feel like I can deal with this though if all I have to do is install twilight forest. Thanks for responding.
